<?php
namespace App\Model\Table;

use Cake\ORM\Table;

class ActivitiesTable extends Table
{
    const ACTIVITY_TYPES = [
        'LARVE_HATCHED' => 'LARVE HATCHED FROM EGGS',
        'LARVE_BRUSHING' => 'BRUSHING LARVE',
        'LARVE_FEEDING' => 'FEEDING LARVE',
        'MOULT_1_STARTED' => '1st MOULT - STARTED',
        'MOULT_1_COMPLETED' => '1st MOULT - COMPLETED',
        'MOULT_1_DUSTING_VIJETHA' => '1ST MOULT - DUSTING DISINFECTANT - VIJETHA 50g/100dfls (30mins BEFORE 1ST FEEDING)',
        'MOULT_1_DUSTING_LIME_POWDER' => '1ST MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
        'MOULT_1_FEEDING' => 'FEEDING FOR 1st MOULT WORMS',
        'MOULT_2_STARTED' => '2nd MOULT STARTED',
        'MOULT_2_COMPLETED' => '2nd MOULT COMPLETED',
        'MOULT_2_DUSTING_VIJETHA' => '2nd MOULT - DUSTING DISINFECTANT - VIJETHA 100g/100dfls (30mins BEFORE 1ST FEEDING)',
        'MOULT_2_DUSTING_LIME_POWDER' => '2nd MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
        'MOULT_2_FEEDING' => 'FEEDING FOR 2nd MOULT WORMS',
        'MOULT_3_STARTED' => '3rd MOULT STARTED',
        'MOULT_3_COMPLETED' => '3rd MOULT COMPLETED',
        'MOULT_3_DUSTING_VIJETHA' => '3rd MOULT - DUSTING DISINFECTANT - VIJETHA 550g/100dfls (30mins BEFORE 1ST FEEDING)',
        'MOULT_3_DUSTING_LIME_POWDER' => '3rd MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
        'MOULT_3_FEEDING' => 'FEEDING FOR 3rd MOULT WORMS',
        'MOULT_4_STARTED' => '4th MOULT STARTED',
        'MOULT_4_COMPLETED' => '4th MOULT COMPLETED',
        'MOULT_4_DUSTING_VIJETHA_1' => '4th MOULT - DUSTING DISINFECTANT - VIJETHA 800g/100dfls (30mins BEFORE 1ST FEEDING)',
        'MOULT_4_DUSTING_VIJETHA_2' => '4th MOULT - DUSTING DISINFECTANT - VIJETHA 1500g/100dfls (30mins BEFORE FEEDING ON 4th DAY)',
        'MOULT_4_DUSTING_LIME_POWDER' => '4th MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
        'MOULT_4_FEEDING' => 'FEEDING FOR 4th MOULT WORMS',
        'SIGNS_OF_SPINNING' => 'SIGNS OF SPINNING',
        'MOUNTING' => 'MOUNTING OF SILKWORMS ON CHANDRIKAS/TRAYS',
        'HARVESTING_COCOONS' => 'HARVESTING COCOONS',
        'MARKETING_OF_COCOONS' => 'MARKETING OF COCOONS',
    ];

    const ACTIVITY_OPTIONS = [
        'Stage 1' => [
            'LARVE_HATCHED' => 'LARVE HATCHED FROM EGGS',
            'LARVE_BRUSHING' => 'BRUSHING LARVE',
            'LARVE_FEEDING' => 'FEEDING LARVE',
        ],

        '-- 1st Moult --' => [
            'MOULT_1_STARTED' => '1st MOULT - STARTED',
            'MOULT_1_COMPLETED' => '1st MOULT - COMPLETED',
        ],

        'Stage 2' => [

            'MOULT_1_DUSTING_VIJETHA' => '1ST MOULT - DUSTING DISINFECTANT - VIJETHA 50g/100dfls (30mins BEFORE 1ST FEEDING)',
            'MOULT_1_DUSTING_LIME_POWDER' => '1ST MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
            'MOULT_1_FEEDING' => 'FEEDING FOR 1st MOULT WORMS',
        ],

        '-- 2nd Moult --' => [
            'MOULT_2_STARTED' => '2nd MOULT STARTED',
            'MOULT_2_COMPLETED' => '2nd MOULT COMPLETED',
        ],

        'Stage 3' => [

            'MOULT_2_DUSTING_VIJETHA' => '2nd MOULT - DUSTING DISINFECTANT - VIJETHA 100g/100dfls (30mins BEFORE 1ST FEEDING)',
            'MOULT_2_DUSTING_LIME_POWDER' => '2nd MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
            'MOULT_2_FEEDING' => 'FEEDING FOR 2nd MOULT WORMS',
        ],

        '-- 3rd Moult --' => [
            'MOULT_3_STARTED' => '3rd MOULT STARTED',
            'MOULT_3_COMPLETED' => '3rd MOULT COMPLETED',
        ],

        'Stage 4' => [

            'MOULT_3_DUSTING_VIJETHA' => '3rd MOULT - DUSTING DISINFECTANT - VIJETHA 550g/100dfls (30mins BEFORE 1ST FEEDING)',
            'MOULT_3_DUSTING_LIME_POWDER' => '3rd MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
            'MOULT_3_FEEDING' => 'FEEDING FOR 3rd MOULT WORMS',
        ],

        '-- 4th Moult --' => [
            'MOULT_4_STARTED' => '4th MOULT STARTED',
            'MOULT_4_COMPLETED' => '4th MOULT COMPLETED',
        ],

        'Stage 5' => [
            'MOULT_4_DUSTING_VIJETHA_1' => '4th MOULT - DUSTING DISINFECTANT - VIJETHA 800g/100dfls (30mins BEFORE 1ST FEEDING)',
            'MOULT_4_DUSTING_VIJETHA_2' => '4th MOULT - DUSTING DISINFECTANT - VIJETHA 1500g/100dfls (30mins BEFORE FEEDING ON 4th DAY)',
            'MOULT_4_DUSTING_LIME_POWDER' => '4th MOULT - DUSTING LIME POWDER (30mins BEFORE FEEDING)',
            'MOULT_4_FEEDING' => 'FEEDING FOR 4th MOULT WORMS',
            'SIGNS_OF_SPINNING' => 'SIGNS OF SPINNING',
            'MOUNTING' => 'MOUNTING OF SILKWORMS ON CHANDRIKAS/TRAYS',
        ],

        '-- Final --' => [
            'HARVESTING_COCOONS' => 'HARVESTING COCOONS',
            'MARKETING_OF_COCOONS' => 'MARKETING OF COCOONS',
        ],
    ];

    const ACTIVITY_ORDER = [
        1100 => 'LARVE_HATCHED',
        1200 => 'LARVE_BRUSHING',
        1300 => 'LARVE_FEEDING',
        1400 => 'LARVE_DUSTING_LIME_POWDER',
        1500 => 'LARVE_DUSTING_DISINFECTANT',

        2100 => 'MOULT_1_STARTED',
        2200 => 'MOULT_1_COMPLETED',
        2300 => 'MOULT_1_DUSTING_VIJETHA',
        2400 => 'MOULT_1_DUSTING_LIME_POWDER',
        2500 => 'MOULT_1_FEEDING',

        3100 => 'MOULT_2_STARTED',
        3200 => 'MOULT_2_COMPLETED',
        3300 => 'MOULT_2_DUSTING_VIJETHA',
        3400 => 'MOULT_2_DUSTING_LIME_POWDER',
        3500 => 'MOULT_2_FEEDING',

        4100 => 'MOULT_3_STARTED',
        4200 => 'MOULT_3_COMPLETED',
        4300 => 'MOULT_3_DUSTING_VIJETHA',
        4400 => 'MOULT_3_DUSTING_LIME_POWDER',
        4500 => 'MOULT_3_FEEDING',

        5100 => 'MOULT_4_STARTED',
        5200 => 'MOULT_4_COMPLETED',
        5300 => 'MOULT_4_DUSTING_VIJETHA_1',
        5400 => 'MOULT_4_DUSTING_VIJETHA_2',
        5500 => 'MOULT_4_DUSTING_LIME_POWDER',
        5600 => 'MOULT_4_FEEDING',

        6100 => 'SIGNS_OF_SPINNING',
        6200 => 'MOUNTING',
        6300 => 'HARVESTING_COCOONS',
        6400 => 'MARKETING_OF_COCOONS',
    ];

    public function initialize(array $config): void
    {
        $this->addBehavior('Timestamp');

        $this->belongsTo('Batches');
    }
}
